#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "element-call"
name = "Element-Call"
description.en = "Group calls powered by Matrix"
description.fr = "Appels de groupe alimentés par Matrix"

version = "0.8.0~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://call.element.io/"
demo = "https://call.element.io/"
code = "https://github.com/vector-im/element-call"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.default_home_server]
    ask.en = "Choose a default Matrix server"
    ask.fr = "Choisissez un serveur Matrix par défault"
    type = "string"
    example = "my-own-homeserver.tld"
    default = "matrix.org"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/vector-im/element-call/archive/refs/tags/v0.8.0.tar.gz"
    sha256 = "c55ae35113c2da19128eed9b85ff81e0edd58f07b215863107d16593a2ac3900"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.livekit]
    amd64.url = "https://github.com/livekit/livekit/releases/download/v1.8.4/livekit_1.8.4_linux_amd64.tar.gz"
    arm64.url = "https://github.com/livekit/livekit/releases/download/v1.8.4/livekit_1.8.4_linux_arm64.tar.gz"
    armv7.url = "https://github.com/livekit/livekit/releases/download/v1.8.4/livekit_1.8.4_linux_armv7.tar.gz"
    amd64.sha256 = "b660f4a72fe493e7c2a27861c403fba3d8c8fec4ce5e223515b26850c24d2dae"
    arm64.sha256 = "02f7a7b252d9bd1298e5bc3e301a138cc7d1bc00dc6855fd4c566ff61fb06324"
    armv7.sha256 = "0157cbb419bc82943c44e4a0548939c04c0f06a4789563f0339de7c359d09814"
    
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset.amd64 = ".*\\.amd64.tar.gz"
    autoupdate.asset.arm64 = ".*\\.arm64.tar.gz"
    autoupdate.asset.armhf = ".*\\.armv7.tar.gz"
    
    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = ""
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
