#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install
ynh_go_install

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.json" --destination="$install_dir/public/config.json"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx
ynh_add_config --template="nginx-livekit.conf" --destination="/etc/nginx/conf.d/$livekit_host_name.$domain.d/$livekit_host_name_server_name.conf" 

#=================================================
# INSTALL THE ELEMENT CALL
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app yarn install
	ynh_hide_warnings ynh_exec_as_app NODE_ENV=production yarn build
popd

#=================================================
# INSTALL THE LIVEKIT
#=================================================
ynh_script_progression "Installing $app-livekit..."

pushd $install_dir/livekit
	ynh_hide_warnings ynh_exec_as_app ./bootstrap.sh
	ynh_hide_warnings ynh_exec_as_app mage
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
